version: '3.4'

services:
  platform-api:
    image: platform-api:v1
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"
    depends_on:
      - "platform-sql-server"

  platform-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${PLATFORM_API_SQL_SERVER_PASSWORD}