# Platform API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      containers:
      - name: platform-api
        image: wuerike/platform-api:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: kube-env

---

# Platform API Cluster IP
apiVersion: v1
kind: Service
metadata:
  name: platform-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platform-api
  ports:
  - name: platform-api
    protocol: TCP
    port: 80
    targetPort: 5000
  - name: platform-api-grpc
    protocol: TCP
    port: 666
    targetPort: 666

---

# Platform API NodePort
apiVersion: v1
kind: Service
metadata:
  name: platform-np-srv
spec:
  type: NodePort
  selector:
    app: platform-api
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000